cities = [
    "AL HAJEB",
    "AGADIR",
    "AL HOCEIMA",
    "ASSA ZAG",
    "AZILAL",
    "BENI MELLAL",
    "BENSLIMANE",
    "BOUJDOUR",
    "BOULEMANE",
    "BERRECHID",
    "CASABLANCA",
    "CHEFCHAOUEN",
    "CHTOUKA AIT BAHA",
    "CHICHAOUA",
    "EL JADIDA",
    "EL KELAA DES SRAGHNAS",
    "ERRACHIDIA",
    "ESSAOUIRA",
    "ES SEMARA",
    "FES",
    "FIGUIG",
    "GUELMIM",
    "IFRANE",
    "KENITRA",
    "KHEMISSET",
    "KHENIFRA",
    "KHOURIBGA",
    "LAAYOUNE",
    "LARACHE",
    "MOHAMMEDIA",
    "MARRAKECH",
    "MEKNES",
    "NADOR",
    "OUARZAZATE",
    "OUJDA",
    "OUED EDDAHAB",
    "RABAT",
    "SALE",
    "TEMARA",
    "SKHIRAT ",
    "SEFROU",
    "SAFI",
    "SETTAT",
    "SIDI KACEM",
    "TANGER",
    "TAN TAN",
    "TAOUNAT",
    "TAROUDANNT",
    "TATA",
    "TAZA",
    "TETOUAN",
    "TIZNIT"
]