"""empty message

Revision ID: 0214c633c4fa
Revises: d1e95fec76a0
Create Date: 2017-03-01 21:23:40.171548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0214c633c4fa'
down_revision = 'd1e95fec76a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('prof_declined', sa.Boolean(), nullable=True))
    op.drop_column('bookings', 'prof_canceled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('prof_canceled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'prof_declined')
    # ### end Alembic commands ###
