"""Upgraded the botifications model

Revision ID: 0c5b41da6179
Revises: 0cab4c771c79
Create Date: 2017-03-31 12:25:11.784398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5b41da6179'
down_revision = '0cab4c771c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('link_endpoint', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('link_kwargs', sa.String(length=500), nullable=True))
    op.add_column('notifications', sa.Column('picture_endpoint', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('picture_kwargs', sa.String(length=500), nullable=True))
    op.drop_column('notifications', 'kwargs_json')
    op.drop_column('notifications', 'endpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('endpoint', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('kwargs_json', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'picture_kwargs')
    op.drop_column('notifications', 'picture_endpoint')
    op.drop_column('notifications', 'link_kwargs')
    op.drop_column('notifications', 'link_endpoint')
    # ### end Alembic commands ###
