"""endpoint to notifications

Revision ID: 0cab4c771c79
Revises: 0c8d41621896
Create Date: 2017-03-30 22:14:49.863574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cab4c771c79'
down_revision = '0c8d41621896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('endpoint', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('kwargs_json', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'kwargs_json')
    op.drop_column('notifications', 'endpoint')
    # ### end Alembic commands ###
