"""empty message

Revision ID: 1930dfe33ef7
Revises: db2405a847b7
Create Date: 2017-03-26 19:08:56.690142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1930dfe33ef7'
down_revision = 'db2405a847b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profs', sa.Column('about_me', sa.String(length=2500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profs', 'about_me')
    # ### end Alembic commands ###
