"""empty message

Revision ID: 1dddb887e41f
Revises: 613d0fdf26e7
Create Date: 2017-02-27 14:53:59.749725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dddb887e41f'
down_revision = '613d0fdf26e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('canceled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'canceled')
    # ### end Alembic commands ###
