"""empty message

Revision ID: 232db3663986
Revises: 0214c633c4fa
Create Date: 2017-03-02 15:42:48.415296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232db3663986'
down_revision = '0214c633c4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('commented', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'commented')
    # ### end Alembic commands ###
