"""empty message

Revision ID: 30edb76627f6
Revises: 7f31684e07a4
Create Date: 2017-02-25 23:29:35.036634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30edb76627f6'
down_revision = '7f31684e07a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'subjects', ['name'])
    op.add_column(u'users', sa.Column('safe_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'safe_name')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_table('bookings')
    # ### end Alembic commands ###
