"""added message to subject model

Revision ID: 4a160bc6affe
Revises: b37f1d2015ee
Create Date: 2017-02-27 13:35:26.135237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a160bc6affe'
down_revision = 'b37f1d2015ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('message', sa.String(length=2500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'message')
    # ### end Alembic commands ###
