"""added 'is_current' column to education and experiences databases

Revision ID: 4df8b64b053d
Revises: 131b2610ac8c
Create Date: 2017-04-11 15:27:23.435237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df8b64b053d'
down_revision = '131b2610ac8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('experiences', sa.Column('is_current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'is_current')
    op.drop_column('educations', 'is_current')
    # ### end Alembic commands ###
