"""Added old_password

Revision ID: 536c2f76b7de
Revises: e4b37b35e80e
Create Date: 2017-03-19 13:38:46.475972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536c2f76b7de'
down_revision = 'e4b37b35e80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('old_pass_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'old_pass_hash')
    # ### end Alembic commands ###
