"""empty message

Revision ID: a40b43ef91a0
Revises: e1049ddc626b
Create Date: 2017-03-30 20:14:53.456918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40b43ef91a0'
down_revision = 'e1049ddc626b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unread_notifications', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unread_notifications')
    # ### end Alembic commands ###
