"""my_migration

Revision ID: a4721f7ff19f
Revises: eba302b1b9a2
Create Date: 2017-02-28 12:47:02.879993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4721f7ff19f'
down_revision = 'eba302b1b9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'test_string', type_=sa.types.String(length=10))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'test_string', type_=sa.types.String(length=2))
    # ### end Alembic commands ###
