"""Simpler app

Revision ID: accf766b7768
Revises: 536c2f76b7de
Create Date: 2017-03-22 21:17:07.469688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'accf766b7768'
down_revision = '536c2f76b7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('client_validated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prof_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_canceled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('prof_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('prof_declined', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('commented', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('feedback_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], [u'clients.id'], name=u'bookings_client_id_fkey'),
    sa.ForeignKeyConstraint(['prof_id'], [u'profs.id'], name=u'bookings_prof_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], [u'subjects.id'], name=u'bookings_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'bookings_pkey')
    )
    # ### end Alembic commands ###
