"""added subjects to profs

Revision ID: b37f1d2015ee
Revises: 30edb76627f6
Create Date: 2017-02-27 12:52:10.691521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37f1d2015ee'
down_revision = '30edb76627f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profs', sa.Column('principal_subject_id', sa.Integer(), nullable=True))
    op.add_column('profs', sa.Column('secondary_subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profs', 'subjects', ['principal_subject_id'], ['id'])
    op.create_foreign_key(None, 'profs', 'subjects', ['secondary_subject_id'], ['id'])
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_constraint(None, 'profs', type_='foreignkey')
    op.drop_constraint(None, 'profs', type_='foreignkey')
    op.drop_column('profs', 'secondary_subject_id')
    op.drop_column('profs', 'principal_subject_id')
    # ### end Alembic commands ###
