"""empty message

Revision ID: b6aa9d397391
Revises: dd29de3218d4
Create Date: 2017-03-01 16:13:14.825561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6aa9d397391'
down_revision = 'dd29de3218d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('client_canceled', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('prof_canceled', sa.Boolean(), nullable=True))
    op.drop_column('bookings', 'canceled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('canceled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'prof_canceled')
    op.drop_column('bookings', 'client_canceled')
    # ### end Alembic commands ###
