"""contacts relationship done right, take 1

Revision ID: c4f6618fc778
Revises: 4434b5fab966
Create Date: 2017-02-24 12:45:36.738698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f6618fc778'
down_revision = '4434b5fab966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_table',
    sa.Column('left_user_id', sa.Integer(), nullable=False),
    sa.Column('right_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['right_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('left_user_id', 'right_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts_table')
    # ### end Alembic commands ###
