"""empty message

Revision ID: c650bba20798
Revises: 1dddb887e41f
Create Date: 2017-02-27 15:39:34.693526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c650bba20798'
down_revision = '1dddb887e41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('prof_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'profs', ['prof_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'prof_id')
    op.drop_column('bookings', 'client_id')
    # ### end Alembic commands ###
