"""empty message

Revision ID: d1e95fec76a0
Revises: b6aa9d397391
Create Date: 2017-03-01 16:16:27.491176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e95fec76a0'
down_revision = 'b6aa9d397391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('prof_accepted', sa.Boolean(), nullable=True))
    op.drop_column('bookings', 'prof_validated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('prof_validated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'prof_accepted')
    # ### end Alembic commands ###
