"""empty message

Revision ID: dab3a6e08826
Revises: accf766b7768
Create Date: 2017-03-22 22:00:28.255947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab3a6e08826'
down_revision = 'accf766b7768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unread_msgs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unread_msgs')
    # ### end Alembic commands ###
