"""empty message

Revision ID: db2405a847b7
Revises: 6dc6402d66fa
Create Date: 2017-03-26 01:36:30.231930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2405a847b7'
down_revision = '6dc6402d66fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profs', sa.Column('hourly_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profs', 'hourly_fee')
    # ### end Alembic commands ###
