"""empty message

Revision ID: dd29de3218d4
Revises: a4721f7ff19f
Create Date: 2017-02-28 15:43:43.159304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd29de3218d4'
down_revision = 'a4721f7ff19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'test_string')
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    op.add_column('clients', sa.Column('test_string', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
