"""relation user status

Revision ID: e1049ddc626b
Revises: 83f5f1ff7d07
Create Date: 2017-03-30 13:58:08.710100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1049ddc626b'
down_revision = '83f5f1ff7d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_status_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'chat_statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'users', 'chat_statuses', ['default_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'status_id')
    op.drop_column('users', 'default_status_id')
    # ### end Alembic commands ###
