"""empty message

Revision ID: e4b37b35e80e
Revises: 232db3663986
Create Date: 2017-03-03 17:58:38.049321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b37b35e80e'
down_revision = '232db3663986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('feedback_message', sa.String(length=1000), nullable=True))
    op.add_column('bookings', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'score')
    op.drop_column('bookings', 'feedback_message')
    # ### end Alembic commands ###
