"""empty message

Revision ID: eba302b1b9a2
Revises: c650bba20798
Create Date: 2017-02-28 12:22:53.558932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba302b1b9a2'
down_revision = 'c650bba20798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('test_string', sa.String(length=2), nullable=True))
    op.alter_column('clients', 'test_string', type_=sa.types.String(length=10))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'test_string')
    # ### end Alembic commands ###
